spring:
  application:
    name: AlgoService


#  config:
#    import: "optional:consul:"
#  cloud:
#    discovery:
#      enabled: false
server:
  servlet:
    context-path: /algoservice
  port: ${PORT:8080}

